language: node_js
node_js:
  - "6"

script:
 - npm run test

after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage


addons:
  code_climate:
  repo_token: e68cd500211d05e6314015e22b415298440d5d29
  
